import React, { useMemo, useState } from 'react';
import { Lock, Sparkles, X } from 'lucide-react';
import type { PlayerState } from '../types';
import { getSkillDefinition } from '../data/skills';
import { CLASS_SKILL_TREES, PASSIVE_DEFINITIONS_V1, PASSIVE_RECIPE_DEFINITIONS, getAdvancedPassiveIds } from '../data/progression/progressionData';
import { craftAdvancedPassive, craftUniquePassive, rollPassiveAwakening, unlockAdvancedActive } from '../data/progression/progressionSystem';

interface Props { playerState:PlayerState; onUpdatePlayer:(s:PlayerState)=>void; onClose:()=>void; }
export const SkillTreeModal:React.FC<Props>=({playerState,onUpdatePlayer,onClose})=>{
  const classId=playerState.combatClass||'NONE'; const nodes=CLASS_SKILL_TREES[classId]||[]; const [selected,setSelected]=useState(nodes[0]?.id||''); const selectedNode=nodes.find(n=>n.id===selected);
  const byId=useMemo(()=>Object.fromEntries(nodes.map(n=>[n.id,n])),[classId]); const prog=playerState.skillProgression;
  const unlocked=new Set(prog?.unlockedTreeNodeIds||[]);
  const nodeLabel=(n:any)=>n.kind==='ACTIVE'?(getSkillDefinition(n.refId||'')?.name||n.name):n.kind==='PASSIVE'?(PASSIVE_DEFINITIONS_V1[n.refId||'']?.name||n.name):n.name;
  const canUseNode=(n:any)=>{if(n.kind==='GATE')return false;if(n.grade==='UNIQUE')return prog?.acquiredUniqueActiveIds.includes(n.refId||'');if(n.kind==='ACTIVE'&&n.grade==='ADVANCED'){const req=n.requiresSkillLevel;return !req||(prog?.skillProgress[req.skillId]?.level||0)>=req.level;}return true;};
  const unlock=()=>{if(!selectedNode?.refId)return;if(selectedNode.kind==='ACTIVE'&&selectedNode.grade==='ADVANCED'){const r=unlockAdvancedActive(playerState,selectedNode.refId);onUpdatePlayer(r.nextState);}};
  const roll=()=>{const r=rollPassiveAwakening(playerState);onUpdatePlayer(r.nextState)};
  const knownRecipes=Object.values(PASSIVE_RECIPE_DEFINITIONS).filter(r=>r.classId===classId&&r.grade==='ADVANCED'&&prog?.knownPassiveRecipeIds.includes(r.id));
  return <div className="fixed inset-0 z-[65] bg-black/85 flex items-center justify-center p-2"><div className="w-full max-w-6xl h-[92dvh] bg-stone-900 border border-stone-800 rounded-2xl overflow-hidden flex flex-col">
    <header className="p-3 border-b border-stone-800 flex items-center"><Sparkles className="w-4 h-4 text-violet-300 mr-2"/><div><b>스킬트리 · 액티브 / 패시브</b><p className="text-xs text-stone-500">목록이 아닌 연결형 나무 구조 · 기본 → 심화 → 유일</p></div><button onClick={onClose} className="ml-auto p-2 bg-stone-800 rounded"><X className="w-4"/></button></header>
    {classId==='NONE'?<div className="m-auto text-center text-stone-400"><Lock className="mx-auto mb-2"/>기본 전직 후 스킬트리가 열립니다.</div>:<div className="flex-1 min-h-0 grid lg:grid-cols-[1fr_350px]">
      <div className="relative overflow-auto bg-stone-950/70 min-h-[600px]"><svg className="absolute inset-0 w-full h-full pointer-events-none">{nodes.flatMap(n=>n.prerequisiteNodeIds.map(pid=>{const p=byId[pid];if(!p)return null;return <line key={`${pid}-${n.id}`} x1={`${p.x}%`} y1={`${p.y}%`} x2={`${n.x}%`} y2={`${n.y}%`} stroke={unlocked.has(n.id)?'#d97706':'#44403c'} strokeWidth="2"/>}))}</svg>{nodes.map(n=>{const isUnlocked=unlocked.has(n.id)||(n.grade==='UNIQUE'&&prog?.acquiredUniqueActiveIds.includes(n.refId||''));const active=selected===n.id;return <button key={n.id} onClick={()=>setSelected(n.id)} style={{left:`calc(${n.x}% - 55px)`,top:`calc(${n.y}% - 28px)`}} className={`absolute z-10 w-[110px] min-h-[56px] rounded-xl border p-2 text-[10px] shadow-xl ${active?'border-amber-400 bg-amber-950':'border-stone-700 bg-stone-900'} ${isUnlocked?'text-stone-100':'text-stone-500'}`}><div className="font-bold">{nodeLabel(n)}</div><div className={`mt-1 ${n.grade==='UNIQUE'?'text-fuchsia-300':n.grade==='ADVANCED'?'text-violet-300':'text-amber-300'}`}>{n.grade}</div>{!isUnlocked&&<Lock className="w-3 h-3 mx-auto mt-1"/>}</button>})}</div>
      <aside className="border-l border-stone-800 p-3 overflow-y-auto space-y-3 text-sm">
        {selectedNode&&<div className="p-3 rounded-xl border border-stone-800"><b>{nodeLabel(selectedNode)}</b><div className="text-xs text-violet-300 mt-1">{selectedNode.kind} · {selectedNode.grade}</div><p className="text-stone-400 mt-2">{selectedNode.description}</p>{selectedNode.kind==='ACTIVE'&&selectedNode.refId&&<>{(() => {const s=getSkillDefinition(selectedNode.refId!);return s?<div className="text-xs mt-2 text-stone-500">COST {s.cost??0} · CD {s.cooldown??0} · Delay {s.actionDelay??1}</div>:null})()}{selectedNode.grade==='BASIC'&&<div className="text-xs mt-2">Lv.{prog?.skillProgress[selectedNode.refId]?.level||1}/20</div>}{selectedNode.grade==='ADVANCED'&&!unlocked.has(selectedNode.id)&&<button disabled={!canUseNode(selectedNode)} onClick={unlock} className="mt-3 w-full p-2 rounded bg-violet-600 disabled:opacity-40">심화 스킬 습득</button>}</>}</div>}
        <div className="p-3 rounded-xl border border-stone-800"><div className="flex justify-between"><b>패시브 해방석</b><span className="text-amber-300">{prog?.passiveAwakeningStones||0}</span></div><button onClick={roll} disabled={(prog?.passiveAwakeningStones||0)<=0} className="w-full mt-2 p-2 rounded bg-amber-600 text-stone-950 font-bold disabled:opacity-40">기본 패시브 추첨</button></div>
        <div className="p-3 rounded-xl border border-stone-800"><b>현재 패시브</b><div className="space-y-1 mt-2">{(Object.values(prog?.passiveProgress||{}) as import('../types').PassiveProgressEntry[]).filter(p=>PASSIVE_DEFINITIONS_V1[p.passiveId]?.classId===classId).map(p=><div key={p.passiveId} className="p-2 bg-stone-950 rounded text-xs flex justify-between"><span>{PASSIVE_DEFINITIONS_V1[p.passiveId]?.name}</span><span>Lv.{p.level} · 중복 {p.copies}</span></div>)}</div></div>
        <div className="p-3 rounded-xl border border-stone-800"><b>심화 패시브 합성</b>{knownRecipes.length===0?<p className="text-xs text-stone-500 mt-2">획득한 조합식이 없습니다. 상점·던전·엘리트 최초 처치·보스에서 획득합니다.</p>:knownRecipes.map(r=><button key={r.id} onClick={()=>{const out=craftAdvancedPassive(playerState,r.id);onUpdatePlayer(out.nextState)}} className="w-full p-2 mt-2 rounded bg-stone-800 text-xs">{PASSIVE_DEFINITIONS_V1[r.resultPassiveId]?.name} 합성</button>)}</div>
        <div className="p-3 rounded-xl border border-fuchsia-900"><b>유일 패시브</b><p className="text-xs text-stone-500 mt-2">모든 심화 패시브 Lv.20 시 변화된 합성식이 열린다.</p><div className="text-xs mt-2">심화: {getAdvancedPassiveIds(classId).map(id=>`${PASSIVE_DEFINITIONS_V1[id]?.name} ${prog?.passiveProgress[id]?.level||0}/20`).join(' · ')}</div><button onClick={()=>{const out=craftUniquePassive(playerState);onUpdatePlayer(out.nextState)}} className="w-full p-2 mt-3 rounded bg-fuchsia-700">유일 합성 도전</button><div className="text-xs text-stone-500 mt-2">잔재 {prog?.uniquePassiveResidue||0} · pity {prog?.uniquePassivePity||0}</div></div>
      </aside>
    </div>}
  </div></div>
}
